### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [SammyT13/CodePath_Flix#1]
Looks like you **did not link your gif walkthrough** for this assignment or it is **not rendering (animating)** properly when viewed in the README 😬. The gif helps us to make sure we don't miss any required or optional stories you have completed.

**Render your gif:**
Once you have uploaded your gif to a site like [imgur](http://imgur.com/) you can render it using the following syntax.

```markdown
<img src="my_gif_address.gif", width=250 />
```

**Make sure you have completed the following steps to completing your README:**

1. Make sure you have the correct README for this assignment, go to the "Setup" section in Assignment Tab for the corresponding week in the [course portal](https://courses.codepath.org).
2. Please mark all implemented stories `[x]`
3. Add a link to your animated gif walkthrough to your README and make sure it renders (animates) when viewing the README.

Your assignment is incomplete until the GIF is valid. Once resolved, please push your updates and **submit your assignment again through the Course Portal (within 48 hours from the posted deadline) so we can regrade it**. We will no longer review resubmissions made after this date.

Still confused about how to properly submit your assignment? Check out the [Submitting Coursework](https://courses.codepath.org/snippets/ios_university/submitting_coursework.md) for detailed instructions.

Whenever you make updates to your project that require re-grading, you need to **re-submit** your project using the submit button on the associated assignment page in the course portal. This will flag your project as “updated” on our end and we know to re-grade.

You should re-submit your assignment anytime you:

- Update a previously incomplete assignment
- Add optional and additional features to an already completed assignment

**Comment by SammyT13** [comment]
Good morning,
I believe there's some mistake, or I do not understand where the issue is.  So where can't the gif image be viewed?  When I go to GitHub, I can view my gifs.  I also did this on Safari and Chrome to ensure there wasn't an issue.  I took a screenshot showing that both browsers showed my gifs.  I even have my README.md file to show I formatted this correctly.  I used the 'recordit' application to do my gifs.  Now, if you're looking at my CodePath submission, I put one gif on the 'gif' field and the remaining two in the notes and explained why.  Can I please get more clarification?  I don't want this to count as my 48-hour extension, as I submitted the work on time and completed it.



Best regards,
Sammy Torres    On Wednesday, September 14, 2022, 05:40:59 AM EDT, CodePath Reviewers ***@***.***> wrote:  
 
 


Looks like you did not link your gif walkthrough for this assignment or it is not rendering (animating) properly when viewed in the README 😬 . The gif helps us to make sure we don't miss any required or optional stories you have completed.

Render your gif:
Once you have uploaded your gif to a site like imgur you can render it using the following syntax.
<img src="my_gif_address.gif", width=250 />
Make sure you have completed the following steps to completing your README:
   
   - Make sure you have the correct README for this assignment, go to the "Setup" section in Assignment Tab for the corresponding week in the course portal.
   - Please mark all implemented stories [x]
   - Add a link to your animated gif walkthrough to your README and make sure it renders (animates) when viewing the README.

Your assignment is incomplete until the GIF is valid. Once resolved, please push your updates and submit your assignment again through the Course Portal (within 48 hours from the posted deadline) so we can regrade it. We will no longer review resubmissions made after this date.

Still confused about how to properly submit your assignment? Check out the Submitting Coursework for detailed instructions.

Whenever you make updates to your project that require re-grading, you need to re-submit your project using the submit button on the associated assignment page in the course portal. This will flag your project as “updated” on our end and we know to re-grade.

You should re-submit your assignment anytime you:
   
   - Update a previously incomplete assignment
   - Add optional and additional features to an already completed assignment

**Comment by codepathreview** [comment]
Hello there, 

Thanks for your response to this feedback. When we opened the GIF links you provided, it says that the Page is Not Found and we can't access them. Our suggestion is you download the GIFs from Recordit and upload them to your Github repository. We can check the GIF in your repository. Feel free to reach out to us if you need any help.  
/cc @codepathreview

**Comment by SammyT13** [comment]
I see. That's not what the provided recordit video said. It just said to copy the URL and paste it into Github. I wish I would have known this because due to limited memory I deleted the gifs. Now I have to redo them plus get penalized for it. Does this mean I'll also ja E to resubmit in the CodePath assignment? Sent from my iPhoneOn Sep 14, 2022, at 08:23, CodePath Reviewers ***@***.***> wrote:﻿
Hello there,
Thanks for your response to this feedback. When we opened the GIF links you provided, it says that the Page is Not Found and we can't access them. Our suggestion is you download the GIFs from Recordit and upload them to your Github repository. We can check the GIF in your repository. Feel free to reach out to us if you need any help.
/cc @codepathreview

**Comment by codepathreview** [comment]
Hello Sammy, 

Thanks for resubmitting your work. We can now se the GIFs in your README. For GIFs that are recorded using Recordit, if the recording gets deleted in Recordit it also gets deleted on other pages it was linked to. We highly suggest that you download the GIF and upload it to your repository so that it will still render on the READMe even if you delet it in Recordit. We hope this information helps.  
/cc @codepathreview
